### ISSUE TITLE
Apple TV 4K pairing request several times an hour when tracing active

### ISSUE THREAD

**Issue by avandorp** [DP-3T/dp3t-app-android#2]
Smartphone: Samsung Galaxy S10e
Next Step version of 2020-04-17 installed from app center (no version information within the app, please add a user visible build identifier)
Several times an hour my smartphone comes up with a bluetooth pairing request for our Apple TV 4K. This happens only when within bluetooth range of our Apple TV 4K and only when the next step app is installed and tracing activated. The pairing request can be accepted or cancelled, but accepting it doesn't resolve the problem as it doesn't actually pair (as seen in the list of bluetooth devices, where it shows up under the available devices but not under the paired devices). Cancelling the request makes it reappear later again as well.
This might be a bug of the Apple TV 4K reacting strangely to whatever the dp3t app does.

**Comment by tcbrouwer** [comment]
Because of the importance of a build identifier, I have created a seperate issue for this. https://github.com/DP-3T/dp3t-app-android/issues/10

**Comment by avandorp** [comment]
Either an update of the apple tv os or the switch to the android tracing API seems to have fixed this issue.
