### ISSUE TITLE
Push an extra error when Bluetooth is deactivated

### ISSUE THREAD

**Issue by Flint4** [DP-3T/dp3t-app-android#23]
It can be hard to users to find out that they have deactivated Bluetooth, if their notification is
 minimized / collapsed. They would need to open the app to find out, something is wrong. 

I'd suggerst to push a separate error message when Bluetooth is deactivated, or change the notification symbol and display an exclamation mark or cross-out the symbol. 

![Screenshot_20200421-202944-2](https://user-images.githubusercontent.com/9900799/79901298-ec2d7780-840f-11ea-93a5-aab07b305723.png)

**Comment by simonroesch** [comment]
This is actually and issue of the https://github.com/DP-3T/dp3t-sdk-android and has been fixed in the SDK. The new sdk version will be included in the demo app soon!
