### ISSUE TITLE
Error on Fairphone2

### ISSUE THREAD

**Issue by HieronymusCH** [DP-3T/dp3t-app-android#59]
The first bug is already reported via the nice person on the hotline. The emails are copied in the folder in our NextCloud. It was recommended to me on irc.chaostreff.ch#ccc that it probably will be better to post all following errors on github. So here we go.

Today my girlfried noticed a new error message you can see in the screenshot with the most actual date.

Screenshots and other data: https://hieronymusch.net/nextcloud/index.php/s/7Ec3WC7ojCQmMtS

**Comment by HieronymusCH** [comment]
Ups, I just realized that there is a "dp3t-app-android-ch" repository.
Should this issue better be posted there?

**Comment by simonroesch** [comment]
Hi @HieronymusCH 
Thank you for the report, very helpful with the screenshots. Please add this to https://github.com/DP-3T/dp3t-app-android-ch/issues/51 where we already track similar issues. Therefore I will close this bug.
