### ISSUE TITLE
SigningConfig "release" is missing required property "storePassword"

### ISSUE THREAD

**Issue by FabrizioCicala** [DP-3T/dp3t-app-android#60]
When executing the command ./gradlew assembleDevRelease I get the following error:

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > SigningConfig "release" is missing required property "storePassword".

How can I fix this problem?

Thank you

**Comment by naomi-albert** [comment]
Have you figured it out? I'm having the same issue.

**Comment by FabrizioCicala** [comment]
Not yet, I was hoping to get some insights here.

**Comment by simonroesch** [comment]
You have to create your own keystore and set the appropriate passwords if you want to build a release build. Debug builds should work out of the box and use your default debug keystore for signing.

**Comment by krim404** [comment]
just to complete this for future requests:
`./gradlew assembleDevDebug`
